### ISSUE TITLE
在mac使用Motrix时，网页显示❌错误，Motrix无法新建任务

### ISSUE THREAD

**Issue by Ada-Wu** [syhyz1990/baiduyun#480]
在以安装网盘助手和网盘直链下载助手后，点击RPC下载发送全部后，chrome页面只显示红色❌，没有额外的错误信息。在motrix软件内也没有看到任务被新建。尝试直接复制链接在motrix里新建任务也无反应。

**Comment by syhyz1990** [comment]
端口号是16800

**Comment by Ada-Wu** [comment]
端口号已经设置为了16800
查看了log里面显示：
`[2020-08-26 12:06:57.909] [warn] [Motrix] Logger init
[2020-08-26 12:06:59.378] [warn] [Motrix] auto sync tracker data: [
  'udp://31.14.40.30:6969/announce\n' +
    '\n' +
    'udp://93.158.213.92:1337/announce\n' +
    '\n' +
    'udp://188.241.58.209:6969/announce\n' +
    '\n' +
    'udp://163.172.217.67:1337/announce\n' +
    '\n' +
    'udp://151.80.120.115:2710/announce\n' +
    '\n' +
    'udp://208.83.20.20:6969/announce\n' +
    '\n' +
    'udp://194.182.165.153:6969/announce\n' +
    '\n' +
    'udp://37.235.174.46:2710/announce\n' +
    '\n' +
    'udp://185.181.60.67:80/announce\n' +
    '\n' +
    'udp://91.216.110.52:451/announce\n' +
    '\n' +
    'udp://5.206.38.65:6969/announce\n' +
    '\n' +
    'udp://185.244.173.140:6969/announce\n' +
    '\n' +
    'udp://176.113.71.60:6961/announce\n' +
    '\n' +
    'udp://51.15.40.114:80/announce\n' +
    '\n' +
    'udp://207.241.231.226:6969/announce\n' +
    '\n' +
    'udp://207.241.226.111:6969/announce\n' +
    '\n',
  'udp://tracker.coppersurfer.tk:6969/announce\n' +
    '\n' +
    'udp://tracker.opentrackr.org:1337/announce\n' +
    '\n' +
    'udp://tracker.leechers-paradise.org:6969/announce\n' +
    '\n' +
    'udp://p4p.arenabg.ch:1337/announce\n' +
    '\n' +
    'http://p4p.arenabg.com:1337/announce\n' +
    '\n' +
    'udp://9.rarbg.to:2710/announce\n' +
    '\n' +
    'udp://9.rarbg.me:2710/announce\n' +
    '\n' +
    'udp://exodus.desync.com:6969/announce\n' +
    '\n' +
    'udp://tracker.cyberia.is:6969/announce\n' +
    '\n' +
    'udp://retracker.lanta-net.ru:2710/announce\n' +
    '\n' +
    'udp://open.stealth.si:80/announce\n' +
    '\n' +
    'udp://tracker.torrent.eu.org:451/announce\n' +
    '\n' +
    'udp://tracker.tiny-vps.com:6969/announce\n' +
    '\n' +
    'udp://tracker.moeking.me:6969/announce\n' +
    '\n' +
    'udp://tracker3.itzmx.com:6961/announce\n' +
    '\n' +
    'http://tracker1.itzmx.com:8080/announce\n' +
    '\n' +
    'udp://ipv4.tracker.harry.lu:80/announce\n' +
    '\n' +
    'udp://bt2.archive.org:6969/announce\n' +
    '\n' +
    'udp://bt1.archive.org:6969/announce\n' +
    '\n' +
    'http://tracker.nyap2p.com:8080/announce\n' +
    '\n'
]
[2020-08-26 17:43:05.718] [warn] [Motrix] UPnPManager unmap 26701 failed, error:  Error: UPnP port mapping failed
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:288:25
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:404:16
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:19:23
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:71:23
    at Request._callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:108:23)
    at self.callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
[2020-08-26 17:43:05.720] [warn] [Motrix] stop UPnP mapping fail UPnP port mapping failed
[2020-08-26 17:43:05.721] [warn] [Motrix] UPnPManager unmap 21301 failed, error:  Error: UPnP port mapping failed
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:288:25
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:404:16
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:19:23
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:71:23
    at Request._callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:108:23)
    at self.callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
[2020-08-26 17:43:05.957] [warn] [Motrix] Logger init
[2020-08-26 17:45:10.372] [warn] [Motrix] UPnPManager unmap 26701 failed, error:  Error: UPnP port mapping failed
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:288:25
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:404:16
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:19:23
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:71:23
    at Request._callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:108:23)
    at self.callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
[2020-08-26 17:45:10.373] [warn] [Motrix] stop UPnP mapping fail UPnP port mapping failed
[2020-08-26 17:45:10.376] [warn] [Motrix] UPnPManager unmap 21301 failed, error:  Error: UPnP port mapping failed
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:288:25
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:404:16
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:19:23
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:71:23
    at Request._callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/device.js:108:23)
    at self.callback (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
[2020-08-26 17:45:10.378] [warn] [Motrix] call client fail: request to http://127.0.0.1:16800/jsonrpc failed, reason: connect ECONNREFUSED 127.0.0.1:16800
[2020-08-26 17:45:41.581] [warn] [Motrix] Logger init
[2020-08-26 17:46:44.742] [warn] [Motrix] Logger init
[2020-08-26 17:48:03.780] [warn] [Motrix] stop UPnP mapping fail Error: [Motrix] port was not specified
    at /Applications/Motrix.app/Contents/Resources/app.asar/dist/electron/main.js:1:182820
    at new Promise (<anonymous>)
    at e.value (/Applications/Motrix.app/Contents/Resources/app.asar/dist/electron/main.js:1:182478)
    at m.<anonymous> (/Applications/Motrix.app/Contents/Resources/app.asar/dist/electron/main.js:1:211083)
    at l (/Applications/Motrix.app/Contents/Resources/app.asar/dist/electron/main.js:1:8367)
    at Generator._invoke (/Applications/Motrix.app/Contents/Resources/app.asar/dist/electron/main.js:1:8120)
    at Generator.forEach.e.<computed> [as next] (/Applications/Motrix.app/Contents/Resources/app.asar/dist/electron/main.js:1:8724)
    at a (/Applications/Motrix.app/Contents/Resources/app.asar/dist/electron/main.js:1:2301)
    at i (/Applications/Motrix.app/Contents/Resources/app.asar/dist/electron/main.js:1:2512)
    at /Applications/Motrix.app/Contents/Resources/app.asar/dist/electron/main.js:1:2571
[2020-08-26 17:48:04.055] [warn] [Motrix] Logger init
[2020-08-26 17:48:05.370] [warn] [Motrix] auto sync tracker data: [
  'udp://93.158.213.92:1337/announce\n' +
    '\n' +
    'udp://163.172.217.67:1337/announce\n' +
    '\n' +
    'udp://151.80.120.114:2710/announce\n' +
    '\n' +
    'udp://208.83.20.20:6969/announce\n' +
    '\n' +
    'udp://194.182.165.153:6969/announce\n' +
    '\n' +
    'udp://5.206.38.65:6969/announce\n' +
    '\n' +
    'udp://37.235.174.46:2710/announce\n' +
    '\n' +
    'udp://185.181.60.67:80/announce\n' +
    '\n' +
    'udp://91.216.110.52:451/announce\n' +
    '\n' +
    'udp://185.244.173.140:6969/announce\n' +
    '\n' +
    'udp://176.113.71.60:6961/announce\n' +
    '\n' +
    'udp://51.15.40.114:80/announce\n' +
    '\n' +
    'udp://207.241.231.226:6969/announce\n' +
    '\n' +
    'udp://207.241.226.111:6969/announce\n' +
    '\n' +
    'udp://46.148.18.250:2710/announce\n' +
    '\n' +
    'udp://46.148.18.254:2710/announce\n' +
    '\n',
  'udp://tracker.coppersurfer.tk:6969/announce\n' +
    '\n' +
    'udp://tracker.opentrackr.org:1337/announce\n' +
    '\n' +
    'udp://p4p.arenabg.ch:1337/announce\n' +
    '\n' +
    'udp://9.rarbg.to:2710/announce\n' +
    '\n' +
    'udp://9.rarbg.me:2710/announce\n' +
    '\n' +
    'udp://exodus.desync.com:6969/announce\n' +
    '\n' +
    'udp://tracker.cyberia.is:6969/announce\n' +
    '\n' +
    'udp://tracker.tiny-vps.com:6969/announce\n' +
    '\n' +
    'udp://retracker.lanta-net.ru:2710/announce\n' +
    '\n' +
    'udp://open.stealth.si:80/announce\n' +
    '\n' +
    'udp://tracker.torrent.eu.org:451/announce\n' +
    '\n' +
    'udp://tracker.moeking.me:6969/announce\n' +
    '\n' +
    'udp://tracker3.itzmx.com:6961/announce\n' +
    '\n' +
    'http://tracker1.itzmx.com:8080/announce\n' +
    '\n' +
    'udp://ipv4.tracker.harry.lu:80/announce\n' +
    '\n' +
    'udp://bt2.archive.org:6969/announce\n' +
    '\n' +
    'udp://bt1.archive.org:6969/announce\n' +
    '\n' +
    'udp://valakas.rollo.dnsabr.com:2710/announce\n' +
    '\n' +
    'udp://opentor.org:2710/announce\n' +
    '\n' +
    'http://tracker.nyap2p.com:8080/announce\n' +
    '\n'
]
[2020-08-26 17:48:07.227] [warn] [Motrix] call client fail: Unauthorized
[2020-08-26 18:06:53.133] [warn] [Motrix] Logger init
[2020-08-26 18:19:22.974] [warn] [Motrix] Logger init
[2020-08-26 18:46:19.943] [warn] [Motrix] Logger init
[2020-08-26 18:46:22.259] [warn] [Motrix] UPnPManager map 21301 failed, error:  Error: UPnP port mapping failed
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:24:23
    at Timeout._onTimeout (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:193:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-08-26 18:46:22.260] [warn] [Motrix] UPnPManager map 26701 failed, error:  Error: UPnP port mapping failed
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
    at /Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:24:23
    at Timeout._onTimeout (/Applications/Motrix.app/Contents/Resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:193:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-08-26 18:46:22.262] [warn] [Motrix] start UPnP mapping fail UPnP port mapping failed
[2020-08-26 19:07:40.310] [warn] [Motrix] Logger init
[2020-08-26 19:07:40.982] [warn] [Motrix] start UPnP mapping fail port was not specified
[2020-08-26 19:46:54.598] [warn] [Motrix] Logger init
[2020-08-26 19:46:55.260] [warn] [Motrix] start UPnP mapping fail port was not specified
`
